name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  ci:
    name: CI - ${{ matrix.os }} - Julia ${{ matrix.julia }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia: [1.9]
        os: [ubuntu-latest] # macos-10.15, windows-2019, macOS-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia Setup
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia }}
      - name: Cache
        uses: julia-actions/cache@v1
        with:
          cache-compiled: "true"
      - name: Build
        uses: julia-actions/julia-buildpkg@v1
      - name: Test
        uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage Process
        uses: julia-actions/julia-processcoverage@v1
      - name: Coverage Upload
        uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
